#!/bin/sh /etc/rc.common

START=98
STOP=15
USE_PROCD=1

PROG=/usr/bin/dockerd
CONFIG=/root/snowball-voice/runtime/daemon.json

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" "--config-file=$CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param term_timeout 60
	procd_set_param limits nofile="1048576 1048576"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
